### ISSUE TITLE
does not work correctly

### ISSUE THREAD

**Issue by varave** [preethamvishy/instagram-node#1]
Hello, I ran your examples, the result: only a few examples work.
![default](https://user-images.githubusercontent.com/16765830/47594064-651a5300-d982-11e8-93da-79ff1ea13b4b.JPG)

**Comment by preethamvishy** [comment]
Instagram has closed the public graphql endpoints that this project uses.

**Comment by varave** [comment]
@preethamvishy, they are accessed if the user is authorized, maybe there is a solution?

**Comment by preethamvishy** [comment]
Yes. If the user is logged in and the URLs are accessed via the browser, valid data is returned. This was not a requirement earlier. 
Instagram kept changing the headers required to access these URLs and I tried to keep up for a while. I am sure that little tweaks to the requests made will get this working. I will try to fix this issue. However, you are welcome to create a PR and I will merge it. :)

**Comment by preethamvishy** [comment]
@inweid I have just added a few fixes :)
