### ISSUE TITLE
Check if user exists

### ISSUE THREAD

**Issue by michael-dm** [preethamvishy/instagram-node#4]
Hello !
Currently the getUserByUsername function throws an error if the instagram user does not exists : 
`/node_modules/instapro/index.js:15
resolve(JSON.parse(eleHTML.split('"ProfilePage":[')[1].split(']},"hostname"')[0]).graphql.user);
TypeError: Cannot read property 'split' of undefined`

Would it be possible to check if the user exists and reject the promise instead ?
Or maybe create a checkUserExistsByUsername function ?

Edit : same for getUserIdFromUsername
Edit 2 : I made a pull request

Thanks !

**Comment by preethamvishy** [comment]
Hey, thanks for adding graceful handling for non-existent users. I have merged the PR and therefore, I'm closing this issue for now.
